version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./config:/app/config
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    restart: always 